datasets:

  A289V:
    data_to_load:
      file_path: "data/EGFR/DCI/A289V/egfr-averaged-dci.csv"
      condition: "A289V"
      swap: false
      start: 1
      myformat: false
    output: 'output/EGFR/A289V'
    title: 'EGFR A289V'
    color: '#2ca02c'

  G598V:
    data_to_load:
      file_path: "data/EGFR/DCI/G598V/egfr-averaged-dci.csv"
      condition: "G598V"
      swap: false
      start: 1
      myformat: false
    output: 'output/EGFR/G598V'
    title: 'EGFR G598V'
    color: '#d62728'
all:
  all_output: 'output/EGFR/all_dfi'
  all_title: 'EGFR Mutations DFI'
  heatmap_dir: 'output/EGFR/heatmaps_A289V_for_WT'
  density_dir: 'output/EGFR/density_plots'
  residues: [845, 920, 992]
