datasets:
  LacI_apo:
    data_to_load:
      file_path: "data/LACI_LLHP_PURR/LACI_APO_DNA_BOUND/pdb_file-dfianalysis.csv"
      condition: "LacI_apo"
      swap: true
      start: 2
      myformat: false
    output: 'output/LACI_PURR_LLHP/LacI_apo'
    title: "LacI_apo"
    color: '#1f77b4'
    score: 'DFI'

  LLHP_apo:
    data_to_load:
      file_path: "data/LACI_LLHP_PURR/LLHP_DNA_BOUND_unbound/PurR-averaged-results.csv"
      condition: "LLHP_apo"
      swap: false
      start: 1
      myformat: false
    output: 'output/LACI_PURR_LLHP/LLHP_apo'
    title: "LLHP_apo"
    color: '#dacd16'
    score: 'DFI'

  PurR_apo:
    data_to_load:
      file_path: "data/LACI_LLHP_PURR/PURR_DNA_BOUND_unbound/PurR-averaged-results.csv"
      condition: "PurR_apo"
      swap: true
      start: 5
      myformat: false
    output: 'output/LACI_PURR_LLHP/PurR_apo'
    title: "PurR_apo"
    color: '#d72380'
    score: 'DFI'
all:
  all_output: 'output/LACI_PURR_LLHP/all_dfi'
  all_title: 'DNA BOUND DFI APO'
  heatmap_dir: output/LACI_LLHP_PURR/heatmaps